
application:
  port: 8080
database:
  host: "127.0.0.1"
  port: 4545
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "david@effect.ai"
